### ISSUE TITLE
Cannot read properties of null (reading 'concat') on Project Breakdown

### ISSUE THREAD

**Issue by philipsabri** [garbetjie/grafana-dashboard-billing-gcp#1]
`Cannot read properties of null (reading 'concat')` on the Project Breakdown chart

![image](https://user-images.githubusercontent.com/80674322/133235362-a2f24bae-0b4f-4569-976d-0fdc96d6a148.png)

Any idea how to fix this?

**Comment by garbetjie** [comment]
@flurreN I haven't been using this dashboard for a while. I can see I'm encountering the same issue.

It appears as if it is related to the structure of the `$source_table` variable. I'll try to make a fix sometime today or tomorrow.
